version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          filters:
            branches:
              only:
                - master
      - cypress/run:
          requires:
            - cypress/install
          command: |
            npm run cy:run:ci
            npm run merge
            npm run generate
          record: true
          parallel: true
          parallelism: 2
          group: 'all tests'
          post-steps:
            - store_test_results:
                path: cypress/results/junit
            - store_artifacts:
                path: cypress/results/report
